joint19_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: kepala_y
    joint_speed: 1.0
    motor:
        id: 19
        init: 2121
        min: 0
        max: 4095

joint20_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: kepala_x
    joint_speed: 1.0
    motor:
        id: 20
        init: 2068
        min: 842
        max: 2600
