joint1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: servo1
    joint_speed: 1.0
    motor:
        id: 1
        init: 2032
        min: 0
        max: 4095

joint2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: servo_2
    joint_speed: 1.0
    motor:
        id: 2
        init: 2024
        min: 0
        max: 4095

joint5_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: servo_5
    joint_speed: 1.0
    motor:
        id: 5
        init: 2055
        min: 0
        max: 4095
