joint17_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: bahu_kanan_pitch
    joint_speed: 0.3
    motor:
        id: 17
        init: 2048
        min: 0
        max: 4095

joint19_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: bahu_kanan_roll
    joint_speed: 0.3
    motor:
        id: 19
        init: 1050
        min: 0
        max: 4095

joint23_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: siku_kanan_pitch
    joint_speed: 0.3
    motor:
        id: 23
        init: 2025
        min: 0
        max: 4095
